apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: apisix
spec:
  project: default
  source:
    chart: apisix
    repoURL: https://apache.github.io/apisix-helm-chart
    targetRevision: 2.12.5
    helm:
      releaseName: apisix
      valueFiles:
        - chart-values-v2.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: apisix
